// <auto-generated />
using System;
using CodeFamily.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeFamily.Data.Migrations
{
    [DbContext(typeof(CodeFamilyDbContext))]
    [Migration("20251115070632_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "dependency_type", new[] { "import", "function_call", "inheritance" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "repo_status", new[] { "queued", "cloning", "analyzing_dependencies", "calculating_ownership", "ready", "error" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "review_state", new[] { "approved", "changes_requested", "commented", "pending" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "webhook_status", new[] { "pending", "processing", "completed", "failed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeFamily.Core.Entities.Commit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.Dependency", b =>
                {
                    b.Property<Guid>("SourceFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("DependencyType")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.HasKey("SourceFileId", "TargetFileId", "DependencyType");

                    b.HasIndex("TargetFileId");

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.FileChange", b =>
                {
                    b.Property<Guid>("CommitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Additions")
                        .HasColumnType("integer");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer");

                    b.HasKey("CommitId", "FileId");

                    b.HasIndex("FileId");

                    b.ToTable("FileChanges");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.FileOwnership", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.HasKey("FileId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FileOwnerships");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.PrFileChange", b =>
                {
                    b.Property<Guid>("PrId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.HasKey("PrId", "FileId");

                    b.HasIndex("FileId");

                    b.ToTable("PrFileChanges");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.PullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GithubPrId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("MergedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PrNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RepositoryId");

                    b.ToTable("PullRequests");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GithubRepoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedByUserId");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.RepositoryCollaborator", b =>
                {
                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RepositoryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RepositoryCollaborators");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.RepositoryFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalLines")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("RepositoryFiles");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<long>("GithubId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.WebhookQueueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WebhookQueue");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.Commit", b =>
                {
                    b.HasOne("CodeFamily.Core.Entities.Repository", "Repository")
                        .WithMany("Commits")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.Dependency", b =>
                {
                    b.HasOne("CodeFamily.Core.Entities.RepositoryFile", "SourceFile")
                        .WithMany("SourceDependencies")
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeFamily.Core.Entities.RepositoryFile", "TargetFile")
                        .WithMany("TargetDependencies")
                        .HasForeignKey("TargetFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceFile");

                    b.Navigation("TargetFile");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.FileChange", b =>
                {
                    b.HasOne("CodeFamily.Core.Entities.Commit", "Commit")
                        .WithMany("FileChanges")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFamily.Core.Entities.RepositoryFile", "File")
                        .WithMany("FileChanges")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commit");

                    b.Navigation("File");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.FileOwnership", b =>
                {
                    b.HasOne("CodeFamily.Core.Entities.RepositoryFile", "File")
                        .WithMany("FileOwnerships")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFamily.Core.Entities.User", "User")
                        .WithMany("FileOwnerships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.PrFileChange", b =>
                {
                    b.HasOne("CodeFamily.Core.Entities.RepositoryFile", "File")
                        .WithMany("PrFileChanges")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFamily.Core.Entities.PullRequest", "PullRequest")
                        .WithMany("FilesChanged")
                        .HasForeignKey("PrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.PullRequest", b =>
                {
                    b.HasOne("CodeFamily.Core.Entities.User", "Author")
                        .WithMany("PullRequests")
                        .HasForeignKey("AuthorId");

                    b.HasOne("CodeFamily.Core.Entities.Repository", "Repository")
                        .WithMany("PullRequests")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.Repository", b =>
                {
                    b.HasOne("CodeFamily.Core.Entities.User", "ConnectedByUser")
                        .WithMany("OwnedRepositories")
                        .HasForeignKey("ConnectedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedByUser");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.RepositoryCollaborator", b =>
                {
                    b.HasOne("CodeFamily.Core.Entities.Repository", "Repository")
                        .WithMany("Collaborators")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFamily.Core.Entities.User", "User")
                        .WithMany("Collaborations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.RepositoryFile", b =>
                {
                    b.HasOne("CodeFamily.Core.Entities.Repository", "Repository")
                        .WithMany("Files")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.Review", b =>
                {
                    b.HasOne("CodeFamily.Core.Entities.PullRequest", "PullRequest")
                        .WithMany("Reviews")
                        .HasForeignKey("PrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFamily.Core.Entities.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.Commit", b =>
                {
                    b.Navigation("FileChanges");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.PullRequest", b =>
                {
                    b.Navigation("FilesChanged");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.Repository", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("Commits");

                    b.Navigation("Files");

                    b.Navigation("PullRequests");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.RepositoryFile", b =>
                {
                    b.Navigation("FileChanges");

                    b.Navigation("FileOwnerships");

                    b.Navigation("PrFileChanges");

                    b.Navigation("SourceDependencies");

                    b.Navigation("TargetDependencies");
                });

            modelBuilder.Entity("CodeFamily.Core.Entities.User", b =>
                {
                    b.Navigation("Collaborations");

                    b.Navigation("FileOwnerships");

                    b.Navigation("OwnedRepositories");

                    b.Navigation("PullRequests");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
